theme = "catppuccin_mocha"

[editor]
default-yank-register = "+"
bufferline = "multiple"
trim-trailing-whitespace = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "│" # Some characters that work well: "▏", "┆", "┊", "⸽", "╎"
skip-levels = 0

[keys.normal]
"end" = "goto_line_end_newline"
"tab" = "indent"
"S-tab" = "unindent"
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_start", "collapse_selection"]
"C-d" = ["extend_to_line_bounds", "yank", "paste_after"]
"esc" = ["keep_primary_selection", "collapse_selection"]
"S-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "flip_selections", "collapse_selection"]
"S-down" = ["extend_to_line_bounds", "delete_selection", "paste_after", "select_mode", "goto_line_start", "normal_mode"]

[keys.select]
"end" = "goto_line_end_newline"
"tab" = "indent"
"S-tab" = "unindent"
"C-left" = "extend_prev_word_start"
"C-right" = "extend_next_word_start"
"C-c" = "yank"
"C-x" = "delete_selection"
"del" = "delete_selection_noyank"

[keys.insert]
"end" = "goto_line_end_newline"
"C-left" = ["move_prev_word_start", "collapse_selection"]
"C-right" = ["move_next_word_start", "collapse_selection"]
